export const QuestionsList = [
    {key: "text_fields",value: "Text"},
    {key: "email",value: "Email"},
    {key: "link",value: "URL"},
    {key: "flaky",value: "Yes / No"},
    {key: "palette",value: "Color Picker"},
    {key: "looks_one",value: "Number"},
    {key: "smartphone",value: "Phone Number"},
    {key: "home",value: "Address"},
    {key: "public",value: "Country"},
    {key: "insert_invitation",value: "Appointment"},
    {key: "calendar_today",value: "Date"},
    {key: "schedule",value: "Time"},
    {key: "check_box",value: "Multiple Choice"},
    {key: "arrow_drop_down",value: "Dropdown"},
    {key: "star",value: "Rating"},
    {key: "portrait",value: "Image Upload"},
    {key: "attach_file",value: "File Upload"},
    {key: "gesture",value: "Signature"},
    {key: "attach_money",value: "Price"},
    {key: "shopping_bag",value: "Product"},
    {key: "loop",value: "Subscriptions"},
    {key: "calculate",value: "Calculation"},
]